### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Konstantinusz** [dfaust/unrar#1]
Hi!

It would be nice to implement one more feature: to delete the volume that already was extracted. So it would be possible to download and extract a a for example 1.4 GB movie splitted in 200 MB parts even when only 1400+200 = 1600 MB space is available on the hard drive. In the usual case it would need 2*1400 = 2800 MB free space to extract - once the full download and once the extraction. This feature would be helpful for example VPS owners who have only a limited space on their VPS-es or extract large files on USB drives, etc.

**Comment by dfaust** [comment]
The problem is, that if something would go wrong, the extracted parts would already be deleted and you would have to re-download them. I don't like deleting data before it's successful processing has been confirmed. That's why I won't implement it. Thanks for your interest though.

**Comment by Konstantinusz** [comment]
Okay, I meant it would be a switch. Currently I am using this Ruby
script to emulate this feature:

https://gist.github.com/Konstantinusz/884db2047a9624aa4d98

2015-02-04 19:41 GMT+01:00, Daniel Faust notifications@github.com:
